language: c
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env: BUILDTYPE=Debug
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env: BUILDTYPE=Release
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env: BUILDTYPE=Debug MY_CC=gcc-5 MY_CXX=g++-5
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BUILDTYPE=Debug
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: BUILDTYPE=Release
    - os: osx
      osx_image: xcode7.3
      env: BUILDTYPE=Debug
    - os: osx
      osx_image: xcode7.3
      env: BUILDTYPE=Release
before_install:
  - umask 022
  - test -n $MY_CC  && export CC=$MY_CC
  - test -n $MY_CXX  && export CXX=$MY_CXX
install: true
script: make && make test
